### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by EricShapiro** [mikefrederick/MFSideMenu#106]
There are some bad interactions between MFSideMenu and iOS 7's status bar:

1: DemoBasic shows the tableview section header overlapping the status bar. This can be fixed by setting a tableview header.

![ios7-tableview-issue](https://f.cloud.github.com/assets/80945/932433/53fe5b8c-0040-11e3-9d64-792befd5f7e5.png)

2: The shadow in the navigation bar looks funny while the menu is being dragged open or closed. 

![ios7-statusbar-navbar-shadow-issue](https://f.cloud.github.com/assets/80945/932435/5cae0098-0040-11e3-8d2b-dbd1827db77b.png)

See attached images.

**Comment by laszlotuss** [comment]
Mine is even worse:
![img_0353](https://f.cloud.github.com/assets/2952613/932501/56525e14-0041-11e3-9a89-10e081545e80.PNG)

**Comment by seviu** [comment]
Same happens for me as well

**Comment by mikefrederick** [comment]
Any ideas as to what the ideal solution to this would be? I agree that it looks bizarre but I am not sure on a solution. If the side menu starts below the status bar, then you just see a black strip above the table view (as @fleshman showed).

**Comment by brycethomas** [comment]
I don't know how much work it would be/whether it's a direction that interests you for this project, but a design like this seems to overcome the issue:

![whatsapp-ios7-sidemenu](https://f.cloud.github.com/assets/119928/979480/9f5b5748-070b-11e3-9047-cd1b4d251d3a.png)

Source: http://dribbble.com/saffad/projects/146739-Whatsapp-iOS-7-Redesign

**Comment by hercrom** [comment]
Tried an ugly way to workaround the trouble on status bar - on somewhere after the view of side menu is created, for example viewDidAppear, changing frame Y origin to -20 and also height +40 seems to do the trick.
As for the style brycethomas commented, I think it is not difficult, just put scale transform in open/close animations. However, the display is messed up if you make the app go to background then back to foreground...

**Comment by mikefrederick** [comment]
@brycethomas I do sort of like that design, but that would be a huge change, not sure everyone would be thrilled about it.

**Comment by pkishino** [comment]
@brycethomas While i do really like that design I do agree with @mikefrederick that it would be a huge change and probably better suited as a separate project. 
It should be possible to add a block up top under status bar on both views and keep the status bar across the views I think.. ill take a look

**Comment by moleksyuk** [comment]
Hi guys,

[This fix](https://github.com/John-Lluch/SWRevealViewController/issues/61#issuecomment-20677579) works fine for me.

**Comment by gfinden** [comment]
The updated Facebook app fades in a strip along the top that gives the status bar a different color as the menu comes out, eliminating any odd appearance issues from the shadow at the top of the screen.

**Comment by mikefrederick** [comment]
@gfinden I saw that, could be a nice feature.

**Comment by fotisp** [comment]
Hello adding this logic to MFSideMenuContainerViewController partially solves the problem

``` objective-c
- (void) setLeftSideMenuFrameToClosedPosition {
....
....
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0) {
        CGRect statusBarFrame =  [[UIApplication sharedApplication] statusBarFrame];
        leftFrame.origin.y = leftFrame.origin.y+statusBarFrame.size.height;
    }
....
....
}

```

Doing the same on for both sides

I have a question opened on SO which details this http://stackoverflow.com/questions/18975920/uisearchbar-overlaps-status-bar-in-ios

Should I open a pull request?

**Comment by gfinden** [comment]
You shouldn't add code that simply sets an offset for the side menus, especially since the height of the status bar can change depending on if there's a call in the background or not, or if an app is recording audio in the background. So maybe this should be handled within apps, since one app developer may choose to actually have a navigation bar in their side menu, where another may not.

I resolved this issue by having my UITableViewController embedded in another UIViewController using UIViewController containment, and then the container view has a constraint that adjusts the container view's top edge based on the status bar height. It works flawlessly.

**Comment by fotisp** [comment]
gfinden that is why the call is not +20, but rather "statusBarFrame.size.height", would you mind sharing the code, or a sample project with that solution

**Comment by paulrolfe** [comment]
I put the LeftSideMenu inside of a UINavigationController. And it looks great, except it disables my ScrollsToTop in all the centerviews for some reason...

```
//First get the tabbarcontroller
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:[NSBundle mainBundle]];
UITabBarController *tbc = [storyboard instantiateViewControllerWithIdentifier:@"MainTabBar"];


//Then put get the left side menu controller, but inside of a navcontroller
SideMenuViewController *leftSideMenuController = [[SideMenuViewController alloc] init];
UINavigationController *leftViewNavigationController = [[UINavigationController alloc] initWithRootViewController:leftSideMenuController];
MFSideMenuContainerViewController *container = [MFSideMenuContainerViewController
                                                containerWithCenterViewController:tbc
                                                leftMenuViewController:leftViewNavigationController                                                    rightMenuViewController:nil];

self.window.rootViewController = container;
[self.window makeKeyAndVisible];
```

**Comment by teenaj** [comment]
Here is my hack for our WeatherRun app:

![weatherrun_sidemenu](https://f.cloud.github.com/assets/5660672/1311676/d5804772-3215-11e3-8aca-a4743728432b.png)

In SideMenuViewController.m

-(void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    AppDelegate _appDelegate =(AppDelegate_)[[UIApplication sharedApplication] delegate];

```
CGRect frame =self.view.frame;
frame.size.height =appDelegate.navController.view.frame.size.height; //-20;


self.view.frame = frame ;

float systemVersion=[[[UIDevice currentDevice] systemVersion] floatValue];
if(systemVersion>=7.0f)
{
    CGRect tempRect;
    for(UIView *sub in [[self view] subviews])
    {
        tempRect = [sub frame];
        tempRect.origin.y += 20.0f; //Height of status bar
        [sub setFrame:tempRect];
    }
}
```

}

And in MFSideMenu.m
- (void)setupMenuContainerView {

.....
rightFrame.origin.y = -20;
....
}

**Comment by brycethomas** [comment]
Just something to look out for for those of you looking to base any calculations off the status bar frame - the status bar frame can report a somewhat strange size when the app is _launched_ in landscape.  As an example, for the center frame I was trying to use a fix like this:

```
- (void)setCenterViewController:(UIViewController *)centerViewController {
    [self removeChildViewControllerFromContainer:_centerViewController];

    _centerViewController = centerViewController;
    if(!_centerViewController) return;

    [self addChildViewController:_centerViewController];
    [self.view addSubview:[_centerViewController view]];
    [_centerViewController didMoveToParentViewController:self];

#pragma mark - Start hotfix for iOS 7 by Bryce Thomas taken from https://github.com/mikefrederick/MFSideMenu/issues/106
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0) {
        CGRect statusBarFrame =  [[UIApplication sharedApplication] statusBarFrame];
        CGRect centerFrame = [_centerViewController view].frame;
        centerFrame.origin.y = centerFrame.origin.y+statusBarFrame.size.height;
        centerFrame.size.height = centerFrame.size.height - statusBarFrame.size.height;
        [_centerViewController view].frame = centerFrame;
    }
#pragma mark - End hotfix for iOS 7
}
```

I was getting a blank screen when _launching_ the app in landscape (worked fine in portrait, and worked fine rotating from portrait to landscape).  After some debugging, I found that the status bar frame height was apparently `1024` at this point in the code (not `20`), so e.g. in the line `centerFrame.size.height = centerFrame.size.height - statusBarFrame.size.height;` was not simply subtracting 20 points, but rather 1024.  Basically, if the app is being launched in landscape, the status bar frame doesn't seem to be a good variable to use.  I had the same issue trying to use the above type of fix on the side menus too.  So, I'm transitioning to the hard-coded value `20`, for now at least until a better solution is proposed.

**Comment by timmolter** [comment]
@fotisp Your solution worked for me. To answer your question, yes, you should open a pull request. Thanks for the fix!

**Comment by ugenlik** [comment]
@fotisp Your solution worked for me as well.
![screen shot 2013-11-06 at 10 29 23 am](https://f.cloud.github.com/assets/1995917/1483494/982fec22-46f8-11e3-9308-9ce9ee043726.png)

#pragma mark -
#pragma mark - Side Menu Positioning
- (void) setLeftSideMenuFrameToClosedPosition {
  if(!self.leftSideMenuViewController) return;
  CGRect leftFrame = self.leftSideMenuViewController.view.frame;
  leftFrame.size.width = self.menuWidth;
  leftFrame.origin.x = (self.menuSlideAnimationEnabled) ? -1*leftFrame.size.width / self.menuSlideFactor : 0;
  if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0) {
      CGRect statusBarFrame =  [[UIApplication sharedApplication] statusBarFrame];
      leftFrame.origin.y = leftFrame.origin.y-statusBarFrame.size.height;
  }else
  {
          leftFrame.origin.y = 0;
  }
  
  self.leftSideMenuViewController.view.frame = leftFrame;
  self.leftSideMenuViewController.view.autoresizingMask = UIViewAutoresizingFlexibleRightMargin|UIViewAutoresizingFlexibleHeight;

}

**Comment by R1ckye** [comment]
It's a bit of a workaround but if anyone is still having this problem, this solved it for me:

```
- (void)setupMenuContainerView {
    if(self.menuContainerView.superview) return;

    self.menuContainerView.frame = self.view.bounds;
    self.menuContainerView.autoresizingMask = UIViewAutoresizingFlexibleHeight|UIViewAutoresizingFlexibleWidth;
    UIViewController *center = (UIViewController *)self.centerViewController;
    CGRect leftFrameWillBe = self.leftMenuViewController.view.frame;
    leftFrameWillBe.size.height = center.view.frame.size.height;
    self.leftMenuViewController.view.frame = leftFrameWillBe;

    [self.view insertSubview:menuContainerView atIndex:0];

    if(self.leftMenuViewController && !self.leftMenuViewController.view.superview) {
        [self.menuContainerView addSubview:self.leftMenuViewController.view];
    }

    if(self.rightMenuViewController && !self.rightMenuViewController.view.superview) {
        [self.menuContainerView addSubview:self.rightMenuViewController.view];
    }
}
```

You have to add a bit of extra functionality to the setup method (around line 100 in MFSideMenuContainerViewController.m) to explicitly set the height of the leftMenuViewController property to the height of the centerViewController.

I had to add the `center` variable, because the centerViewController is an `id` and I can't call `view` directly on it, but I think it's safe to assume that it's going to be a `UIViewController` or some subclass of it, like `UINavigationController`.

I'm gonna submit a pull request to this sometime, but the project seems quite abandoned so I don't have too much hope for it to be merged, but until then, just replace that function with this one.

FYI, don't do

```
    self.leftMenuViewController.view.frame = center.view.frame
```

It sets the width to a wrong value, only set the height of the frame's size, not the frame property itself!

**Comment by UBBproject** [comment]
Hi, guys!
I was suffering a whole weekend. Finally found the best solution:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  }
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation
  {
  [self.theTableView setContentInset:UIEdgeInsetsMake(0, self.theTableView.contentInset.left, self.theTableView.contentInset.bottom, self.theTableView.contentInset.right)];
  }

**Comment by mikefrederick** [comment]
I believe this should be solved in #153. Sorry it took so long guys.

**Comment by manonthemoon42** [comment]
Hi,

I still have this the space on the bottom of my left menu... 

![screen shot 2014-11-03 at 11 29 59](https://cloud.githubusercontent.com/assets/2165625/4881122/bcab5582-6344-11e4-811b-e77df8b829c0.png)

I use the last version of this pod. 
I tried to figure out how to fix it by checking other issues, I couldn't find any solution.

The only one thing that worked, was the solution of @fotisp, I've just updated a lil bit because his solution add an extra space on the top.

The solution I used : 

```
- (void) setLeftSideMenuFrameToClosedPosition {
  ....
  ....
 if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0) {
      CGRect statusBarFrame =  [[UIApplication sharedApplication] statusBarFrame];
      leftFrame.size.height = leftFrame.size.height+statusBarFrame.size.height;
 }
 ....
 ....
}
```

Any help please ?

**Comment by awedeebawe** [comment]
I took the piece of code by @teenaj and edited it as follows and it worked (but I also have another manipulation for the table):

```
-(void) viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    CGRect frame = [[UIScreen mainScreen] bounds];

    self.view.frame = frame ;

    float systemVersion=[[[UIDevice currentDevice] systemVersion] floatValue];
    if(systemVersion>=7.0f)
    {
        CGRect tempRect;
        for(UIView *sub in [[self view] subviews])
        {
            tempRect = [sub frame];
            [sub setFrame:tempRect];
        }
        self.tableView.contentInset = UIEdgeInsetsMake(20.0f, 0.0f, 20.0f, 0.0f);

    }
}
```
