### ISSUE TITLE
Side menu doesn't fit to screen height

### ISSUE THREAD

**Issue by eliganim** [mikefrederick/MFSideMenu#72]
If my nib file is designed for 3.5" size, then the side menu doesn't stretch to fit a 4" screen and vice versa. I only see this happen if my SideMenuViewController is not a UITableViewController, but a normal UIViewController with a table view in it.
The view and TableView both have flexible height attribute.

This is how it look on 3.5":
![iOS Simulator Screen shot Apr12 2013 3 12 48 PM](https://f.cloud.github.com/assets/850349/372738/c72eda10-a36a-11e2-949c-ca2bf5f8aefa.png)

This is how it looks on 4":
![iOS Simulator Screen shot Apr12 2013 3 14 28 PM](https://f.cloud.github.com/assets/850349/372739/d66247d8-a36a-11e2-9c6a-05e8fb063be0.png)

**Comment by mikefrederick** [comment]
Interesting. I am doing a pretty big update to the library relatively soon and I am pretty sure it will fix this issue. Stay tuned.

**Comment by eliganim** [comment]
OK, great. Thanks for the fast reply and for sharing your code on github!

**Comment by eliganim** [comment]
Any news about that update?

**Comment by mikefrederick** [comment]
There is a branch called view_controller_containment you could take a look at for the time being -- it should fix this issue. But it is definitely still in development, been pretty busy lately but hoping to come out with a new version soon.

**Comment by mikefrederick** [comment]
The update I was working on is now on master. Please checkout the README, this issue is now fixed.

**Comment by eliganim** [comment]
Thanks for your hard work!
Unfortunately, it still doesn't work. Now it always assumes that the
content is 4". If I use the SideMenu on a 3.5" device, then the bottom part
of the side menu is unreachable.

Simply add this line "NSLog(@"%@", self.view);" to the viewDidLoad method of your controllers, and check if the frame actually fits itself to the screen size.

**Comment by mikefrederick** [comment]
Hmm thought I tested this out. I will reopen it until I get a chance to address it -- hang tight.

**Comment by mikefrederick** [comment]
@Ganem have you been able to reproduce this on both the left and right menus? Any chance it is only happening on the left menu?

**Comment by eliganim** [comment]
Yes, it looks like it only happens on the left menu.

**Comment by mikefrederick** [comment]
@Ganem I just pushed a few commits, any chance you could verify for me that the issue has been resolved? I want to make sure that I was seeing the same issue that you were before I close this issue.

**Comment by eliganim** [comment]
@mikefrederick Looks ok now. I've tested both left/right side and 3.5"/4". Thanks.
